# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Ubuntu 24.04

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: sudo apt update && sudo apt install libmpv-dev gcc libegl1-mesa-dev xorg-dev

    - name: Install Fyne tool
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Fyne package
      run: make package_linux

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Supersonic_ubuntu_x64.tar.xz
        path: Supersonic.tar.xz
