# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Mac x64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install Dependencies
      run: brew install --force mpv && brew install --force dylibbundler

    - name: Setup path
      run: export C_INCLUDE_PATH=/usr/local/include:/opt/homebrew/include:$C_INCLUDE_PATH && export LIBRARY_PATH=/usr/local/lib:/opt/homebrew/lib:$LIBRARY_PATH

    - name: Install Fyne tool
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Build and package app bundles
      run: >
        make package_macos &&
        cp -r Supersonic.app Supersonic.app.2 &&
        make bundledeps_macos_homebrew && make zip_macos &&
        mv Supersonic.zip Supersonic_BigSur+.zip &&
        rm -r Supersonic.app &&
        mv Supersonic.app.2 Supersonic.app &&
        make bundledeps_macos_highsierra && make zip_macos &&
        mv Supersonic.zip Supersonic_HighSierra+.zip

    - name: Upload Big Sur+ package
      uses: actions/upload-artifact@v4
      with:
        name: Supersonic_mac_x64_BigSur+.zip
        path: Supersonic_BigSur+.zip

    - name: Upload High Sierra+ package
      uses: actions/upload-artifact@v4
      with:
        name: Supersonic_mac_x64_HighSierra+.zip
        path: Supersonic_HighSierra+.zip

